### ISSUE TITLE
Cannot load chunky_png

### ISSUE THREAD

**Issue by natejump24** [g1eny0ung/Alfred-Colors-workflow#2]
I am running Alfred v4.6.1 on an M1 Max MacBook Pro and I am running into the following issue:

```
[21:26:55.746] Logging Started...
[21:27:07.846] Colors[Script Filter] Queuing argument '#'
[21:27:08.007] Colors[Script Filter] Script with argv '(null)' finished
[21:27:08.011] ERROR: Colors[Script Filter] Code 1: <internal:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- chunky_png (LoadError)
	from <internal:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from colors.rb:4:in `<main>'
```

I have Ruby v3.0.3 and `chunky_png` installed so thinking it may be a symlink issue?

```
➜  ~ ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]

➜  ~ gem list --local | grep chunky_png
chunky_png (1.4.0)
```

Any ideas?

Thanks in advance :)

**Comment by g1eny0ung** [comment]
Maybe something wrong with `PATHS`. Can u show me the output of the `gem environment`?

**Comment by sungentim** [comment]
![image](https://user-images.githubusercontent.com/3905397/153104482-a3cad593-5e0d-43ac-b25d-98d3445b167a.png)

**Comment by sungentim** [comment]
![image](https://user-images.githubusercontent.com/3905397/153105091-3da46bc1-424b-4a42-93d6-ff2706930d39.png)

**Comment by g1eny0ung** [comment]
@sungentim Can u show me the output of the `gem environment`?

**Comment by sungentim** [comment]
![image](https://user-images.githubusercontent.com/3905397/153310192-cde7c83e-5e9e-42a3-b884-7a2b283e37df.png)

**Comment by g1eny0ung** [comment]
Seems `ruby` and `gem` have mismatched versions. You can see `gem` is from the `rvm` manager but the workflow expects homebrew installed `ruby`.

The solution is very ez, you can edit the workflow script to replace the corresponding `bin/ruby` if it's not from homebrew:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/15034155/153331750-69c7e1c0-f14b-4ecc-af96-a19b92c0da54.png">

**Comment by LevyLizzz** [comment]
> Seems `ruby` and `gem` have mismatched versions. You can see `gem` is from the `rvm` manager but the workflow expects homebrew installed `ruby`.
> 
> The solution is very ez, you can edit the workflow script to replace the corresponding `bin/ruby` if it's not from homebrew:
> 
> <img alt="image" width="916" src="https://user-images.githubusercontent.com/15034155/153331750-69c7e1c0-f14b-4ecc-af96-a19b92c0da54.png">
<img width="1848" alt="iShot2022-05-16 17 26 13" src="https://user-images.githubusercontent.com/11754722/168562026-020575c6-afad-4a3b-af2a-d21f689cd3ef.png">
can't work

**Comment by g1eny0ung** [comment]
@LevyLizzz Should be placed in `else` because your machine is an arm architecture.

**Comment by LevyLizzz** [comment]
> 

tried it, can' work eithe
<img width="1180" alt="iShot2022-05-16 17 53 03" src="https://user-images.githubusercontent.com/11754722/168567092-65a01fa5-6c42-498c-bab2-bc87d24301b3.png">
r

**Comment by g1eny0ung** [comment]
@LevyLizzz Turning on debug mode may show why the error is occurring:

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/15034155/168576070-216c370d-3700-48c2-92c5-6328c92d2064.png">

**Comment by LevyLizzz** [comment]
@g1eny0ung solved, appreciate it!
